version: '3.4'

services:
  mongo:
    image: mongo
    container_name: 'mongodbcontainer'
    ports:
       - '27017:27017'

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    depends_on: 
        - mongo
    restart: always
    ports: 
        - 5000:80
    build:
      context: .
      dockerfile: Dockerfile