version: '3.4'

services:
  mongo:
    image: mongo
    container_name: 'mongodbcontainer'
    ports:
       - '27017:27017'

  webapi:
    image: webapi
    container_name: 'webapicontainer'
    depends_on: 
        - mongo
    restart: always
    ports: 
        - 5000:80
    build:
      context: .
      dockerfile: ./Presentation/WebApi/Dockerfile

  blazorapp:
     image: blazorapp
     container_name: 'blazorappcontainer'
     build:
       context: .
       dockerfile: ./Presentation/BlazorApp/Dockerfile
     ports:
       - 9000:80